export type EnumCountry = {
  id: string;
  name: string;
  name_jp: string;
};

const enumCountries = [
  { id: 'ISL', name: 'Iceland', name_jp: 'アイスランド' },
  { id: 'IRL', name: 'Ireland', name_jp: 'アイルランド' },
  { id: 'AZE', name: 'Azerbaijan', name_jp: 'アゼルバイジャン' },
  { id: 'AFG', name: 'Afghanistan', name_jp: 'アフガニスタン' },
  { id: 'ARE', name: 'United Arab Emirates', name_jp: 'アラブ首長国連邦' },
  { id: 'DZA', name: 'Algeria', name_jp: 'アルジェリア' },
  { id: 'ARG', name: 'Argentina', name_jp: 'アルゼンチン' },
  { id: 'ABW', name: 'Aruba', name_jp: 'アルバ' },
  { id: 'ALB', name: 'Albania', name_jp: 'アルバニア' },
  { id: 'ARM', name: 'Armenia', name_jp: 'アルメニア' },
  { id: 'AIA', name: 'Anguilla', name_jp: 'アンギラ' },
  { id: 'AGO', name: 'Angola', name_jp: 'アンゴラ' },
  {
    id: 'ATG',
    name: 'Antigua and Barbuda',
    name_jp: 'アンティグア・バーブーダ',
  },
  { id: 'AND', name: 'Andorra', name_jp: 'アンドラ' },
  { id: 'YEM', name: 'Yemen', name_jp: 'イエメン' },
  { id: 'ISR', name: 'Israel', name_jp: 'イスラエル' },
  { id: 'ITA', name: 'Italy', name_jp: 'イタリア' },
  { id: 'IRQ', name: 'Iraq', name_jp: 'イラク' },
  { id: 'IRN', name: 'Iran', name_jp: 'イラン' },
  { id: 'IND', name: 'India', name_jp: 'インド' },
  { id: 'IDN', name: 'Indonesia', name_jp: 'インドネシア' },
  { id: 'WAK', name: 'Wake Island', name_jp: 'ウェーク島' },
  { id: 'UGA', name: 'Uganda', name_jp: 'ウガンダ' },
  { id: 'UKR', name: 'Ukraine', name_jp: 'ウクライナ' },
  { id: 'UZB', name: 'Uzbekistan', name_jp: 'ウズベキスタン' },
  { id: 'URY', name: 'Uruguay', name_jp: 'ウルグアイ' },
  { id: 'GBR', name: 'UK', name_jp: '英国' },
  {
    id: 'IOT',
    name: 'British Indian Ocean Territory',
    name_jp: '英領インド洋地域',
  },
  { id: 'VGB', name: 'British Virgin Islands', name_jp: '英領バージン諸島' },
  { id: 'ECU', name: 'Ecuador', name_jp: 'エクアドル' },
  { id: 'EGY', name: 'Egypt', name_jp: 'エジプト' },
  { id: 'EST', name: 'Estonia', name_jp: 'エストニア' },
  { id: 'SWZ', name: 'Eswatini', name_jp: 'エスワティニ' },
  { id: 'ETH', name: 'Ethiopia', name_jp: 'エチオピア' },
  { id: 'ERI', name: 'Eritrea', name_jp: 'エリトリア' },
  { id: 'SLV', name: 'El Salvador', name_jp: 'エルサルバドル' },
  { id: 'AUS', name: 'Australia', name_jp: 'オーストラリア' },
  { id: 'AUT', name: 'Austria', name_jp: 'オーストリア' },
  { id: 'OMN', name: 'Oman', name_jp: 'オマーン' },
  { id: 'NLD', name: 'Netherlands', name_jp: 'オランダ' },
  { id: 'ANT', name: 'Netherlands Antilles', name_jp: 'オランダ領アンティル' },
  { id: 'CPV', name: 'Cape Verde', name_jp: 'カーボヴェルデ' },
  { id: 'KAZ', name: 'Kazakhstan', name_jp: 'カザフスタン' },
  { id: 'KAS', name: 'Kashmir', name_jp: 'カシミール' },
  { id: 'QAT', name: 'Qatar', name_jp: 'カタール' },
  { id: 'CAN', name: 'Canada', name_jp: 'カナダ' },
  { id: 'CMR', name: 'Cameroon', name_jp: 'カメルーン' },
  { id: 'KHM', name: 'Cambodia', name_jp: 'カンボジア' },
  { id: 'GHA', name: 'Ghana', name_jp: 'ガーナ' },
  { id: 'GUY', name: 'Guyana', name_jp: 'ガイアナ' },
  { id: 'GAB', name: 'Gabon', name_jp: 'ガボン' },
  { id: 'GMB', name: 'Gambia', name_jp: 'ガンビア' },
  { id: 'PRK', name: 'North Korea', name_jp: '北朝鮮' },
  { id: 'MKD', name: 'North Macedonia', name_jp: '北マケドニア' },
  { id: 'MNP', name: 'Northern Mariana Islands', name_jp: '北マリアナ諸島' },
  { id: 'CYP', name: 'Cyprus', name_jp: 'キプロス' },
  { id: 'CUB', name: 'Cuba', name_jp: 'キューバ' },
  { id: 'KIR', name: 'Kiribati', name_jp: 'キリバス' },
  { id: 'KGZ', name: 'Kyrgyzstan', name_jp: 'キルギス' },
  { id: 'GIN', name: 'Guinea', name_jp: 'ギニア' },
  { id: 'GNB', name: 'Guinea-Bissau', name_jp: 'ギニアビサウ' },
  { id: 'GRC', name: 'Greece', name_jp: 'ギリシャ' },
  { id: 'KWT', name: 'Kuwait', name_jp: 'クウェート' },
  { id: 'COK', name: 'Cook Islands', name_jp: 'クック諸島' },
  { id: 'CXR', name: 'Christmas island', name_jp: 'クリスマス島' },
  { id: 'HRV', name: 'Croatia', name_jp: 'クロアチア' },
  { id: 'GTM', name: 'Guatemala', name_jp: 'グアテマラ' },
  { id: 'GLP', name: 'Guadeloupe', name_jp: 'グアドループ島' },
  { id: 'GUM', name: 'Guam', name_jp: 'グアム' },
  { id: 'GRL', name: 'Greenland', name_jp: 'グリーンランド' },
  { id: 'GRD', name: 'Grenada', name_jp: 'グレナダ' },
  { id: 'CYM', name: 'Cayman Islands', name_jp: 'ケイマン諸島' },
  { id: 'KEN', name: 'Kenya', name_jp: 'ケニア' },
  { id: 'CIV', name: "Cote D'Ivoire", name_jp: 'コートジボワール' },
  { id: 'CCK', name: 'Cocos Islands', name_jp: 'ココス諸島' },
  { id: 'CRI', name: 'Costa Rica', name_jp: 'コスタリカ' },
  { id: 'COM', name: 'Comoros Union', name_jp: 'コモロ連合' },
  { id: 'COL', name: 'Columbia', name_jp: 'コロンビア' },
  { id: 'COG', name: 'Republic of the Congo', name_jp: 'コンゴ共和国' },
  {
    id: 'COD',
    name: 'Democratic Republic of the Congo',
    name_jp: 'コンゴ民主共和国',
  },
  { id: 'SAU', name: 'Saudi Arabia', name_jp: 'サウジアラビア' },
  { id: 'WSM', name: 'Samoa', name_jp: 'サモア' },
  { id: 'STP', name: 'Sao Tome Principe', name_jp: 'サントメ・プリンシペ' },
  {
    id: 'SPM',
    name: 'Saint Pierre and Micron',
    name_jp: 'サンピエール島・ミクロン島',
  },
  { id: 'SMR', name: 'San Marino', name_jp: 'サンマリノ' },
  { id: 'ZMB', name: 'Zambia', name_jp: 'ザンビア' },
  { id: 'SLE', name: 'Sierra Leone', name_jp: 'シエラレオネ' },
  { id: 'SYR', name: 'Syria', name_jp: 'シリア' },
  { id: 'SGP', name: 'Singapore', name_jp: 'シンガポール' },
  { id: 'DJI', name: 'Djibouti', name_jp: 'ジブチ' },
  {
    id: 'SJM',
    name: 'Svalbard and Jan Mayen Islands',
    name_jp: 'スバールバル諸島・ヤンマイエン諸島',
  },
  { id: 'JAM', name: 'Jamaica', name_jp: 'ジャマイカ' },
  { id: 'GEO', name: 'Georgia', name_jp: 'ジョージア' },
  { id: 'JON', name: 'Johnston Island', name_jp: 'ジョンストン島' },
  { id: 'ZWE', name: 'Zimbabwe', name_jp: 'ジンバブエ' },
  { id: 'SDN', name: 'Sudan', name_jp: 'スーダン' },
  { id: 'CHE', name: 'Switzerland', name_jp: 'スイス' },
  { id: 'SWE', name: 'Sweden', name_jp: 'スウェーデン' },
  { id: 'CHI', name: 'Channel Islands', name_jp: 'チャネル諸島' },
  { id: 'ESP', name: 'Spain', name_jp: 'スペイン' },
  { id: 'SUR', name: 'Suriname', name_jp: 'スリナム' },
  { id: 'LKA', name: 'Sri Lanka', name_jp: 'スリランカ' },
  { id: 'SVK', name: 'Slovakia', name_jp: 'スロバキア' },
  { id: 'SVN', name: 'Slovenia', name_jp: 'スロベニア' },
  { id: 'SYC', name: 'Seychelles', name_jp: 'セイシェル' },
  { id: 'GNQ', name: 'Equatorial Guinea', name_jp: '赤道ギニア' },
  { id: 'SEN', name: 'Senegal', name_jp: 'セネガル' },
  { id: 'SRB', name: 'Serbia', name_jp: 'セルビア' },
  {
    id: 'KNA',
    name: 'Saint Kitts and Nevis',
    name_jp: 'セントクリストファー・ネイビス',
  },
  {
    id: 'VCT',
    name: 'Saint Vincent and the Grenadines',
    name_jp: 'セントビンセント及びグレナディーン諸島',
  },
  { id: 'SHN', name: 'St. Helena', name_jp: 'セントヘレナ島' },
  { id: 'LCA', name: 'Saint Lucia', name_jp: 'セントルシア' },
  { id: 'SOM', name: 'Somalia', name_jp: 'ソマリア' },
  { id: 'SLB', name: 'Solomon Islands', name_jp: 'ソロモン諸島' },
  {
    id: 'TCA',
    name: 'Turks and Caicos Islands',
    name_jp: 'タークス諸島・カイコス諸島',
  },
  { id: 'THA', name: 'Sea ​​bream', name_jp: 'タイ' },
  { id: 'TWN', name: 'Taiwan', name_jp: '台湾' },
  { id: 'TJK', name: 'Tajikistan', name_jp: 'タジキスタン' },
  { id: 'TZA', name: 'Tanzania', name_jp: 'タンザニア' },
  { id: 'KOR', name: 'South Korea', name_jp: '大韓民国' },
  { id: 'CZE', name: 'Czech', name_jp: 'チェコ' },
  { id: 'TCD', name: 'Chad', name_jp: 'チャド' },
  { id: 'FRO', name: 'Faroe Islands', name_jp: 'フェロー諸島' },
  { id: 'CAF', name: 'Central Africa', name_jp: '中央アフリカ' },
  { id: 'CHN', name: 'China', name_jp: '中国' },
  { id: 'TUN', name: 'Tunisia', name_jp: 'チュニジア' },
  { id: 'CHL', name: 'Chile', name_jp: 'チリ' },
  { id: 'TUV', name: 'Tuvalu', name_jp: 'ツバル' },
  { id: 'DNK', name: 'Denmark', name_jp: 'デンマーク' },
  { id: 'TGO', name: 'Togo', name_jp: 'トーゴ' },
  { id: 'TKL', name: 'Tokelau Islands', name_jp: 'トケラウ諸島' },
  {
    id: 'TTO',
    name: 'Republic of Trinidad and Tobago',
    name_jp: 'トリニダード・トバゴ',
  },
  { id: 'TKM', name: 'Turkmenistan', name_jp: 'トルクメニスタン' },
  { id: 'TUR', name: 'Turkey', name_jp: 'トルコ' },
  { id: 'TON', name: 'Tonga', name_jp: 'トンガ' },
  { id: 'DEU', name: 'Germany', name_jp: 'ドイツ' },
  { id: 'DOM', name: 'Dominican Republic', name_jp: 'ドミニカ共和国' },
  { id: 'DMA', name: 'Dominica', name_jp: 'ドミニカ国' },
  { id: 'NGA', name: 'Nigeria', name_jp: 'ナイジェリア' },
  { id: 'NRU', name: 'Nauru', name_jp: 'ナウル' },
  { id: 'NAM', name: 'Namibia', name_jp: 'ナミビア' },
  { id: 'ATA', name: 'Antarctica', name_jp: '南極大陸' },
  { id: 'NIU', name: 'Niue', name_jp: 'ニウエ' },
  { id: 'NIC', name: 'Nicaragua', name_jp: 'ニカラグア' },
  { id: 'ESH', name: 'Western Sahara', name_jp: '西サハラ' },
  { id: 'NER', name: 'Niger', name_jp: 'ニジェール' },
  { id: 'NCL', name: 'New Caledonia', name_jp: 'ニューカレドニア' },
  { id: 'NZL', name: 'New Zealand', name_jp: 'ニュージーランド' },
  { id: 'NPL', name: 'Nepal', name_jp: 'ネパール' },
  { id: 'NFK', name: 'Norfolk Island', name_jp: 'ノーフォーク島' },
  { id: 'NOR', name: 'Norway', name_jp: 'ノルウェー' },
  { id: 'HTI', name: 'Haiti', name_jp: 'ハイチ' },
  { id: 'HUN', name: 'Hungary', name_jp: 'ハンガリー' },
  { id: 'BHR', name: 'Bahrain', name_jp: 'バーレーン' },
  { id: 'VAT', name: 'Vatican City', name_jp: 'バチカン市国' },
  { id: 'VUT', name: 'Vanuatu', name_jp: 'バヌアツ' },
  { id: 'BHS', name: 'Bahamas', name_jp: 'バハマ' },
  { id: 'BMU', name: 'Bermuda', name_jp: 'バミューダ諸島' },
  { id: 'BRB', name: 'Barbados', name_jp: 'バルバドス' },
  { id: 'BGD', name: 'Bangladesh', name_jp: 'バングラディシュ' },
  { id: 'PAK', name: 'Pakistan', name_jp: 'パキスタン' },
  { id: 'PAN', name: 'Panama', name_jp: 'パナマ' },
  { id: 'PNG', name: 'Papua New Guinea', name_jp: 'パプアニューギニア' },
  { id: 'PLW', name: 'Palau', name_jp: 'パラオ' },
  { id: 'PRY', name: 'Paraguay', name_jp: 'パラグアイ' },
  { id: 'PSE', name: 'Palestine', name_jp: 'パレスチナ' },
  { id: 'TLS', name: 'East Timor', name_jp: '東ティモール' },
  { id: 'PCN', name: 'Pitcairn Islands', name_jp: 'ピトケアン島' },
  { id: 'FJI', name: 'Fiji Islands', name_jp: 'フィジー諸島' },
  { id: 'PHL', name: 'Philippines', name_jp: 'フィリピン' },
  { id: 'FIN', name: 'Finland', name_jp: 'フィンランド' },
  { id: 'IMN', name: 'Isle of Man', name_jp: 'マン島' },
  {
    id: 'FLK',
    name: 'Falkland (Malvinas) Islands',
    name_jp: 'フォークランド（マルビナス）諸島',
  },
  { id: 'FRA', name: 'France', name_jp: 'フランス' },
  { id: 'GUF', name: 'French Guiana', name_jp: 'フランス領ギアナ' },
  { id: 'PYF', name: 'French Polynesia', name_jp: 'フランス領ポリネシア' },
  { id: 'BTN', name: 'Bhutan', name_jp: 'ブータン' },
  { id: 'BRA', name: 'Brazil', name_jp: 'ブラジル' },
  { id: 'BGR', name: 'Bulgaria', name_jp: 'ブルガリア' },
  { id: 'BFA', name: 'Burkina Faso', name_jp: 'ブルキナファソ' },
  { id: 'BRN', name: 'Brunei', name_jp: 'ブルネイ' },
  { id: 'BDI', name: 'Burundi', name_jp: 'ブルンジ' },
  { id: 'PRI', name: 'Puerto Rico', name_jp: 'プエルトリコ' },
  { id: 'USA', name: 'USA', name_jp: '米国' },
  { id: 'ASM', name: 'American Samoa', name_jp: '米領サモア' },
  { id: 'VIR', name: 'US Virgin Islands', name_jp: '米領バージン諸島' },
  { id: 'VNM', name: 'Vietnam', name_jp: 'ベトナム' },
  { id: 'BEN', name: 'Benin', name_jp: 'ベナン' },
  { id: 'VEN', name: 'Venezuela', name_jp: 'ベネズエラ' },
  { id: 'BLR', name: 'Belarus', name_jp: 'ベラルーシ' },
  { id: 'BLZ', name: 'Belize', name_jp: 'ベリーズ' },
  { id: 'BEL', name: 'Belgium', name_jp: 'ベルギー' },
  { id: 'PER', name: 'Peru', name_jp: 'ペルー' },
  { id: 'HKG', name: 'Hong Kong', name_jp: '香港' },
  { id: 'HND', name: 'Honduras', name_jp: 'ホンジュラス' },
  {
    id: 'BIH',
    name: 'Bosnia-Herzegovina',
    name_jp: 'ボスニア・ヘルツェゴビナ',
  },
  { id: 'BWA', name: 'Botswana', name_jp: 'ボツワナ' },
  { id: 'BOL', name: 'Bolivia', name_jp: 'ボリビア' },
  { id: 'POL', name: 'Poland', name_jp: 'ポーランド' },
  { id: 'PRT', name: 'Portugal', name_jp: 'ポルトガル' },
  { id: 'MHL', name: 'Marshall Islands', name_jp: 'マーシャル諸島' },
  { id: 'MYT', name: 'Mayotte Island', name_jp: 'マイヨット島' },
  { id: 'MAC', name: 'Macau', name_jp: 'マカオ' },
  { id: 'MDG', name: 'Madagascar', name_jp: 'マダガスカル' },
  { id: 'MWI', name: 'Malawi', name_jp: 'マラウイ' },
  { id: 'MLI', name: 'Mali', name_jp: 'マリ' },
  { id: 'MLT', name: 'Malta', name_jp: 'マルタ' },
  { id: 'MTQ', name: 'Martinique', name_jp: 'マルチニーク島' },
  { id: 'MYS', name: 'Malaysia', name_jp: 'マレーシア' },
  {
    id: 'FSM',
    name: 'Federated States of Micronesia',
    name_jp: 'ミクロネシア連邦',
  },
  { id: 'MID', name: 'Midway Islands', name_jp: 'ミッドウェー諸島' },
  { id: 'ZAF', name: 'South Africa', name_jp: '南アフリカ' },
  { id: 'MMR', name: 'Myanmar', name_jp: 'ミャンマー' },
  { id: 'MEX', name: 'Mexico', name_jp: 'メキシコ' },
  { id: 'MUS', name: 'Mauritius', name_jp: 'モーリシャス' },
  { id: 'MRT', name: 'Mauritania', name_jp: 'モーリタニア' },
  { id: 'MOZ', name: 'Mozambique', name_jp: 'モザンビーク' },
  { id: 'MCO', name: 'Monaco', name_jp: 'モナコ' },
  { id: 'MDV', name: 'Maldives', name_jp: 'モルディブ' },
  { id: 'MDA', name: 'Moldova', name_jp: 'モルドバ' },
  { id: 'MAR', name: 'Morocco', name_jp: 'モロッコ' },
  { id: 'MNG', name: 'Mongolia', name_jp: 'モンゴル' },
  { id: 'MSR', name: 'Moncellat', name_jp: 'モンセラット' },
  { id: 'MNE', name: 'Montenegro', name_jp: 'モンテネグロ' },
  { id: 'JOR', name: 'Jordan', name_jp: 'ヨルダン' },
  { id: 'LAO', name: 'Laos', name_jp: 'ラオス' },
  { id: 'LVA', name: 'Latvia', name_jp: 'ラトビア' },
  { id: 'LTU', name: 'Lithuania', name_jp: 'リトアニア' },
  { id: 'LIE', name: 'Liechtenstein', name_jp: 'リヒテンシュタイン' },
  { id: 'LBY', name: 'Libya', name_jp: 'リビア' },
  { id: 'LBR', name: 'Liberia', name_jp: 'リベリア' },
  { id: 'ROU', name: 'Romania', name_jp: 'ルーマニア' },
  { id: 'GIB', name: 'Gibraltar', name_jp: 'ジブラルタル' },
  { id: 'LUX', name: 'Luxembourg', name_jp: 'ルクセンブルク' },
  { id: 'RWA', name: 'Rwanda', name_jp: 'ルワンダ' },
  { id: 'LSO', name: 'Lesotho', name_jp: 'レソト' },
  { id: 'LBN', name: 'Lebanon', name_jp: 'レバノン' },
  { id: 'REU', name: 'Reunion', name_jp: 'レユニオン' },
  { id: 'RUS', name: 'Russia', name_jp: 'ロシア' },
  { id: 'WLF', name: 'Wallis Futuna Islands', name_jp: 'ワリス・フテュナ諸島' },
] as EnumCountry[];

export default enumCountries.sort((a: EnumCountry, b: EnumCountry) =>
  a.name > b.name ? 1 : -1
);
